name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup proxy
      env:
        http_proxy: http://117.68.38.149:35917
        https_proxy: http://117.68.38.149:35917
      run: |
        echo "http_proxy=$http_proxy" >> ~/.bashrc
        echo "https_proxy=$https_proxy" >> ~/.bashrc
        source ~/.bashrc
        echo "Proxy set to $http_proxy and $https_proxy"

    - name: Login to Alibaba Cloud Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        registry: crpi-d7vdgkzyxv14k7rt.cn-hangzhou.personal.cr.aliyuncs.com

    - name: Pull image
      run: docker pull crpi-d7vdgkzyxv14k7rt.cn-hangzhou.personal.cr.aliyuncs.com/kube-cross1111/kube-cross1111:v1.23.0-go1.17.5-bullseye.0

    - name: Push image
      run: |
        docker tag crpi-d7vdgkzyxv14k7rt.cn-hangzhou.personal.cr.aliyuncs.com/kube-cross1111/kube-cross1111:v1.23.0-go1.17.5-bullseye.0 crpi-d7vdgkzyxv14k7rt.cn-hangzhou.personal.cr.aliyuncs.com/kube-cross1111/kube-cross1111:v1.23.0-go1.17.5-bullseye.0
        docker push crpi-d7vdgkzyxv14k7rt.cn-hangzhou.personal.cr.aliyuncs.com/kube-cross1111/kube-cross1111:v1.23.0-go1.17.5-bullseye.0
